### PR TITLE
Accept dynamic radius

### PR DESCRIPTION
**Pull request by kmpoppe**
Couldn't get any dev environment to run in a short amount of time.
Would this work?

### CODE REVIEW

**Comment by thomersch** [comment]
I just allowed the test suite to run, let's see. Thanks for taking the time to add tests for this.

I must admit, I don't love the two vs. three parameter distinction. I think an extra get query parameter, e.g. `around_radius`, would be much cleaner.

**Comment by kmpoppe** [comment]
Updated to it's own parameter. The first run of the Workflow failed, but I couldn't really figure out what it was complaining about, it just threw some very inpolite emojis at me 😂

**Comment by thomersch** [comment]
I told the CI to be nice, but it doesn't seem to listen to me.

The project uses [black](https://github.com/psf/black) to enforce consistent formatting and fails the workflow if the code style diverges from it.

Just a minor nitpick: Maybe it'd be nice to have an upper limit for the distance parameter to prevent enormous lookups. Something like 250 km perhaps?

**Comment by kmpoppe** [comment]
I shall take a look at the white spacing later, I might have mixed that up.

250k sounds good, will implement a fail condition.

**Comment by kmpoppe** [comment]
Well the last test failed because idiot me forgot a `:` 🤦, I've added an upper bound, and `0` not being a valid value, should've added < 0 as well, but would love to see if black is now happy.

**Comment by kmpoppe** [comment]
black still wants to reformat views.py, https://black.vercel.app/ suggest going from 521 to 568 lines, so it's not only my commit that's causing an issue... Do you want to redo views.py completely?

**Comment by thomersch** [comment]
I ran the formatter locally and it only reformatted some of the changed lines. That web tool probably didn't take into consideration that we allow 120 char line lengths.

Tests are passing, I validated the changes locally. Let's get this deployed! Thanks!

**Comment by kmpoppe** [comment]
Don't mention it, it's you allowing a change that was just a preparation for a long process ahead :-)

**Comment by kmpoppe** [comment]
Works pefectly!
https://osmcal.org/?around=54.6558,10.0255&around_radius=97 => zero results
https://osmcal.org/?around=54.6558,10.0255&around_radius=97.5 => 3 Stammtische in Lübeck, which are in 97.32 km distance!
Nice :)

**Pull request merged**
